### ISSUE TITLE
Unable to Print the saved images on My App.

### ISSUE THREAD

**Issue by ABBIGADDU** [looped-labs/CIE-Sample-App#2]
Hi,

I Hope You are Doing well.

I am Writing the code like these...!

mPrinter.printsavedimage(R.drawable.logo);

is not working. Please Tell me how can i print...!

**Comment by ntha314159** [comment]
This Library is intended to be used with CIE Thermal Printers.

The Documentation can be found here in the [docs section](https://github.com/looped-labs/CIE-Sample-App/tree/master/docs)
